/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function detect(text: string): Info | null
export function detectLang(text: string): Lang | null
export function detectScript(text: string): Script | null
export type JsInfo = Info
export class Info {
  constructor(script: JsScript, lang: JsLang, confidence: number)
  get lang(): JsLang
  get script(): JsScript
  get confidence(): number
  get isReliable(): boolean
}
export type JsLang = Lang
export class Lang {
  static withCode(code: LangCode): Lang
  static withCodeISO6391(code: LangCodeISO6391): Lang
  get code(): LangCode
  get codeISO6391(): LangCodeISO6391
  get name(): string
  get engName(): string
  static all(): Array<Lang>
}
export type JsScript = Script
export class Script {
  constructor()
  get name(): string
  get langs(): Array<Lang>
  static all(): Array<Script>
}
export type JsDetector = Detector
export class Detector {
  constructor()
  static withAllowlist(list: (LangCode | LangCodeISO6391)[]): JsDetector
  static withDenylist(list: (LangCode | LangCodeISO6391)[]): JsDetector
  detect(text: string): Info | null
  detectLang(text: string): Lang | null
  detectScript(text: string): Script | null
}
